# Klasifikasi

apa itu klasifikasi? <br>
klasifikasi adalah proses untuk mengidentifikasi dari model untuk menghasilkan data sebutan dari proses training

# Load data

In [ ]:
from sklearn.datasets import load_iris
iris_datasets = load_iris()

In [ ]:
print("Jenis isian dari dataset iris = \n{}".format(iris_datasets.keys()))

Jenis isian dari dataset iris = 
dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])


In [ ]:
print("Target name = \n{}".format(iris_datasets['target_names']))

Target name = 
['setosa' 'versicolor' 'virginica']


In [ ]:
print("Feature name = ",format(iris_datasets['feature_names']))

Feature name =  ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


In [ ]:
print("data name = \n{}".format(iris_datasets['data'][:5])) #menampilkan 5 data saja

data name = 
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]


In [ ]:
print("Target = \n{}".format(iris_datasets['target']))
# jenis bunga iris
# 0 = 'setosa', 2 = 'versicolor', 3 = 'virginica'

Target = 
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


In [ ]:
# melihat tipe data pada data
print('tipe data = {}'.format(type(iris_datasets['data'])))
print('tipe target = {}'.format(type(iris_datasets['target'])))

tipe data = <class 'numpy.ndarray'>
tipe target = <class 'numpy.ndarray'>


In [ ]:
print('ukuran data, (kolom)= {}'.format(iris_datasets['data'].shape)) # 150 baris dan 4 kolom
print('ukuran target = {}'.format(iris_datasets['target'].shape)) # 150 baris dan 1 kolom

ukuran data, (kolom)= (150, 4)
ukuran target = (150,)


# proses Training dan Testing

langkah pertama: membagi data 150 data menjadi data untuk training dan data untuk testing <br>
kita coba membagi data Training (75%) dan data testing(25%)

In [ ]:
from sklearn.model_selection import train_test_split
#  x = data, y =target
x_train, x_test, y_train, y_test = train_test_split(
    iris_datasets['data'],iris_datasets['target'], test_size=0.25,random_state=0)
# rando_state = 0 -> kalau di run ulang , isi data yang dibagi tetap sama

In [ ]:
# jumlah data training
print('x_train shape = {}'.format(x_train.shape)) # data = (['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)'])
print('y_train shape = {}'.format(y_train.shape)) # Target = (sentosa, versicolor, viginica)

x_train shape = (112, 4)
y_train shape = (112,)


In [ ]:
# jumlah data training
print('x_test shape = {}'.format(x_test.shape)) # data = (['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)'])
print('y_test shape = {}'.format(y_test.shape)) # Target = (sentosa, versicolor, viginica)

x_test shape = (38, 4)
y_test shape = (38,)


# proses training

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=1)

In [ ]:
knn.fit(x_train,y_train)

KNeighborsClassifier(n_neighbors=1)

melakukan presiksi

In [ ]:
import numpy as np
x_baru = np.array([[3, 2.1, 5, 1.2]])
prediksi = knn.predict(x_baru)
print('hasil prediksi Model knn = {}'.format(prediksi))
print('hasil prediksi Model knn pake nama = {}'.format(iris_datasets['target_names'][prediksi]))

hasil prediksi Model knn = [2]
hasil prediksi Model knn pake nama = ['virginica']


# Evaluasi Model


In [ ]:
y_pred = knn.predict(x_test)
print(y_pred)

[2 1 0 2 0 2 0 1 1 1 2 1 1 1 1 0 1 1 0 0 2 1 0 0 2 0 0 1 1 0 2 1 0 2 2 1 0
 2]


In [ ]:
print('hasil Akurasi model = {}'.format(knn.score(x_test, y_test)))
# hasil akurasi 97% bener

hasil Akurasi model = 0.9736842105263158


# test 1.0

In [ ]:
from sklearn.model_selection import train_test_split
#  x = data, y =target
x_train, x_test, y_train, y_test = train_test_split(
    iris_datasets['data'],iris_datasets['target'], test_size=0.1,random_state=0)
# rando_state = 0 -> kalau di run ulang , isi data yang dibagi tetap sama

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
knn3 = KNeighborsClassifier(n_neighbors=1)

In [ ]:
knn3.fit(x_train,y_train)

KNeighborsClassifier(n_neighbors=1)

In [ ]:
# jumlah data training
print('x_train shape = {}'.format(x_train.shape)) # data = (['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)'])
print('y_train shape = {}'.format(y_train.shape)) # Target = (sentosa, versicolor, viginica)

x_train shape = (135, 4)
y_train shape = (135,)


In [ ]:
print('hasil Akurasi model = {}'.format(knn3.score(x_test, y_test)))
# hasil akurasi 97% bener

hasil Akurasi model = 1.0


# TUGAS

In [ ]:
from sklearn.datasets import load_breast_cancer
data_cancer = load_breast_cancer()

In [ ]:
print("Jenis isian dari dataset iris = \n{}".format(data_cancer.keys()))

Jenis isian dari dataset iris = 
dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])


In [ ]:
print("Target name = \n{}".format(data_cancer['target_names']))

Target name = 
['malignant' 'benign']


In [ ]:
print("Feature name = ",format(data_cancer['feature_names']))

Feature name =  ['mean radius' 'mean texture' 'mean perimeter' 'mean area'
 'mean smoothness' 'mean compactness' 'mean concavity'
 'mean concave points' 'mean symmetry' 'mean fractal dimension'
 'radius error' 'texture error' 'perimeter error' 'area error'
 'smoothness error' 'compactness error' 'concavity error'
 'concave points error' 'symmetry error' 'fractal dimension error'
 'worst radius' 'worst texture' 'worst perimeter' 'worst area'
 'worst smoothness' 'worst compactness' 'worst concavity'
 'worst concave points' 'worst symmetry' 'worst fractal dimension']


In [ ]:
print('ukuran data, (kolom)= {}'.format(data_cancer['data'].shape))
print('ukuran target = {}'.format(data_cancer['target'].shape))

ukuran data, (kolom)= (569, 30)
ukuran target = (569,)


In [ ]:
print("data name = \n{}".format(data_cancer['data'][:5])) #menampilkan 5 data saja

data name = 
[[1.799e+01 1.038e+01 1.228e+02 1.001e+03 1.184e-01 2.776e-01 3.001e-01
  1.471e-01 2.419e-01 7.871e-02 1.095e+00 9.053e-01 8.589e+00 1.534e+02
  6.399e-03 4.904e-02 5.373e-02 1.587e-02 3.003e-02 6.193e-03 2.538e+01
  1.733e+01 1.846e+02 2.019e+03 1.622e-01 6.656e-01 7.119e-01 2.654e-01
  4.601e-01 1.189e-01]
 [2.057e+01 1.777e+01 1.329e+02 1.326e+03 8.474e-02 7.864e-02 8.690e-02
  7.017e-02 1.812e-01 5.667e-02 5.435e-01 7.339e-01 3.398e+00 7.408e+01
  5.225e-03 1.308e-02 1.860e-02 1.340e-02 1.389e-02 3.532e-03 2.499e+01
  2.341e+01 1.588e+02 1.956e+03 1.238e-01 1.866e-01 2.416e-01 1.860e-01
  2.750e-01 8.902e-02]
 [1.969e+01 2.125e+01 1.300e+02 1.203e+03 1.096e-01 1.599e-01 1.974e-01
  1.279e-01 2.069e-01 5.999e-02 7.456e-01 7.869e-01 4.585e+00 9.403e+01
  6.150e-03 4.006e-02 3.832e-02 2.058e-02 2.250e-02 4.571e-03 2.357e+01
  2.553e+01 1.525e+02 1.709e+03 1.444e-01 4.245e-01 4.504e-01 2.430e-01
  3.613e-01 8.758e-02]
 [1.142e+01 2.038e+01 7.758e+01 3.861e+02 1.425e-01 2.

## training dan test

In [ ]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(
    data_cancer['data'],data_cancer['target'], test_size=0.25,random_state=0)

In [ ]:
# jumlah data training
print('x_train shape = {}'.format(x_train.shape))
print('y_train shape = {}'.format(y_train.shape))

x_train shape = (426, 30)
y_train shape = (426,)


In [ ]:
from sklearn.neighbors import KNeighborsClassifier
model_cancer = KNeighborsClassifier(n_neighbors=1)

In [ ]:
model_cancer.fit(x_train,y_train)

KNeighborsClassifier(n_neighbors=1)

## Evaluasi

In [ ]:
print('hasil Akurasi model = {}'.format(model_cancer.score(x_test, y_test)))

hasil Akurasi model = 0.916083916083916


uh modelnya pintar


<br>
<a href="https://www.linkedin.com/in/m-riziq-sa"><img src="https://img.shields.io/badge/-© 2024 M. Riziq Sirfatullah Alfarizi-417DAC?style=for-the-badge&logoColor=white"/></a>